name: Build Firmware

# Trigger on push or pull request to main/master branches
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container: zephyrprojectrtos/ci:v0.26.13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: application

      
      - name: Initialize Zephyr Workspace
        run: |
          west init -l application
          west update
          west zephyr-export

      
      - name: Build Engine ECU (NUCLEO-G474RE)
        run: |
          cd application
          west build -p always -b nucleo_g474re firmware/ecu_engine

      - name: Build Body ECU (NUCLEO-H723ZG)
        run: |
          cd application
          west build -p always -b nucleo_h723zg firmware/ecu_body
